name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace 'main' with your branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allow actions to push to the repo

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" 

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Copy CNAME file
        run: |
          if [ -f CNAME ]; then
            cp CNAME dist/
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Deploy content from the 'dist' folder
          publish_branch: gh-pages
          force_orphan: true  # Force orphan commit, no branch history
